import type { Metadata } from "next";
import localFont from "next/font/local"; // If you're not using it, you can remove this line
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Suspense } from "react";
import  {DashboardProvider}  from '@/helpers/dashboardContext';
import { ApiProvider } from '@/helpers/apiContext'; // Adjust the import path as necessary
import Script from "next/script";

export const metadata: Metadata = {
  title: "academy.w3era",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: {
  children: React.ReactNode;
}
)
 {
  return (
    <html lang="en">
      <head>
      <Script
          defer
          id="gtag"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KJ2PJCWP');
          `,
          }}
        />
    
      </head>
      <body suppressHydrationWarning={true} className="antialiased">
       
<noscript
          dangerouslySetInnerHTML={{
            __html: `
                <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KJ2PJCWP"
height="0" width="0" style="display:none;visibility:hidden"></iframe>
          `,
          }}
        />
        <Toaster />
        <DashboardProvider> 
        <ApiProvider>       
            {children}
        </ApiProvider>
          </DashboardProvider>
      </body>
    </html>
  );
}
